import numpy as np
import json
from pathlib import Path

NUMERIC_FEATURES = [
    "price_rub",
    "calories",
    "protein_g",
    "carbs_g",
    "fat_g",
    "sugar_g",
]

CATEGORY_FEATURES = [
    "cat_bowl",
    "cat_dessert",
    "cat_drink",
    "cat_protein_plate",
    "cat_salad",
    "cat_side",
]

TAG_FEATURES = [
    "tag_apple",
    "tag_avocado",
    "tag_bakery",
    "tag_balanced",
    "tag_bbq",
    "tag_berry",
    "tag_bold_flavor",
    "tag_bowl",
    "tag_bread",
    "tag_buffalo",
    "tag_caesar",
    "tag_caffeine",
    "tag_carb",
    "tag_cashew",
    "tag_casual",
    "tag_chicken",
    "tag_chocolate",
    "tag_citrus",
    "tag_classic",
    "tag_cola",
    "tag_comfort",
    "tag_creamy",
    "tag_crispy",
    "tag_crunchy",
    "tag_dessert",
    "tag_drink",
    "tag_fall_flavor",
    "tag_fish",
    "tag_fresh",
    "tag_fruit",
    "tag_functional",
    "tag_greens",
    "tag_healthy",
    "tag_hearty",
    "tag_high_calorie",
    "tag_high_protein",
    "tag_hot",
    "tag_hot_honey",
    "tag_hummus",
    "tag_italian_note",
    "tag_kombucha",
    "tag_lemonade",
    "tag_light",
    "tag_light_snack",
    "tag_low_calorie",
    "tag_low_carb",
    "tag_mediterranean",
    "tag_mezze",
    "tag_mushroom",
    "tag_premium",
    "tag_plant_based",
    "tag_protein",
    "tag_ranch",
    "tag_rice",
    "tag_salad",
    "tag_salmon",
    "tag_sesame",
    "tag_side",
    "tag_snack",
    "tag_soda",
    "tag_sparkling",
    "tag_spicy",
    "tag_steak",
    "tag_sweet",
    "tag_sweet_potato",
    "tag_tea",
    "tag_tofu",
    "tag_umami",
    "tag_unsweetened",
    "tag_vegetarian",
    "tag_warm",
    "tag_water",
    "tag_zero_calorie",
]

FEATURE_NAMES = NUMERIC_FEATURES + CATEGORY_FEATURES + TAG_FEATURES

MENU_ITEMS = [
    {
        "index": 1,
        "name": "Салат с курицей и кунжутом",
        "price_rub": 560,
        "calories": 615,
        "protein_g": 35,
        "carbs_g": 54,
        "fat_g": 29,
        "sugar_g": 21,
        "category": "protein_plate",
        "tags": ["chicken", "salad", "sesame", "healthy", "balanced"],
    },
    {
        "index": 2,
        "name": "Стейк с карамелизованным чесноком",
        "price_rub": 630,
        "calories": 770,
        "protein_g": 34,
        "carbs_g": 82,
        "fat_g": 31,
        "sugar_g": 0,
        "category": "protein_plate",
        "tags": ["steak", "hot", "hearty", "protein", "premium"],
    },
    {
        "index": 3,
        "name": "Лосось в мисо-глазури",
        "price_rub": 665,
        "calories": 930,
        "protein_g": 35,
        "carbs_g": 88,
        "fat_g": 48,
        "sugar_g": 0,
        "category": "protein_plate",
        "tags": ["salmon", "fish", "premium", "hearty", "high_calorie"],
    },
    {
        "index": 4,
        "name": "Курица в остро-сладком медовом соусе",
        "price_rub": 595,
        "calories": 875,
        "protein_g": 49,
        "carbs_g": 68,
        "fat_g": 41,
        "sugar_g": 0,
        "category": "protein_plate",
        "tags": ["chicken", "hot", "sweet", "hearty", "high_protein"],
    },
    {
        "index": 5,
        "name": "Стейк с гарниром мезе",
        "price_rub": 630,
        "calories": 755,
        "protein_g": 34,
        "carbs_g": 76,
        "fat_g": 38,
        "sugar_g": 0,
        "category": "protein_plate",
        "tags": ["steak", "mezze", "rice", "premium", "hearty"],
    },
    {
        "index": 6,
        "name": "Боул «Урожай» с курицей и бататом",
        "price_rub": 560,
        "calories": 740,
        "protein_g": 32,
        "carbs_g": 60,
        "fat_g": 41,
        "sugar_g": 0,
        "category": "bowl",
        "tags": ["chicken", "bowl", "sweet_potato", "healthy", "fall_flavor"],
    },
    {
        "index": 7,
        "name": "Боул с хрустящим рисом и курицей",
        "price_rub": 525,
        "calories": 640,
        "protein_g": 28,
        "carbs_g": 61,
        "fat_g": 30,
        "sugar_g": 0,
        "category": "bowl",
        "tags": ["chicken", "bowl", "crispy", "balanced", "casual"],
    },
    {
        "index": 8,
        "name": "Боул с курицей, песто и пармезаном",
        "price_rub": 525,
        "calories": 525,
        "protein_g": 35,
        "carbs_g": 38,
        "fat_g": 23,
        "sugar_g": 0,
        "category": "bowl",
        "tags": ["chicken", "bowl", "light", "high_protein", "italian_note"],
    },
    {
        "index": 9,
        "name": "Боул с курицей, авокадо и соусом ранч",
        "price_rub": 560,
        "calories": 715,
        "protein_g": 23,
        "carbs_g": 59,
        "fat_g": 42,
        "sugar_g": 0,
        "category": "bowl",
        "tags": ["chicken", "avocado", "ranch", "creamy", "comfort"],
    },
    {
        "index": 10,
        "name": "Тёплый веганский боул с грибами",
        "price_rub": 490,
        "calories": 635,
        "protein_g": 18,
        "carbs_g": 50,
        "fat_g": 42,
        "sugar_g": 0,
        "category": "bowl",
        "tags": ["tofu", "vegetarian", "umami", "plant_based", "mushroom"],
    },
    {
        "index": 11,
        "name": "Боул с лососем и соусом тако",
        "price_rub": 630,
        "calories": 835,
        "protein_g": 36,
        "carbs_g": 62,
        "fat_g": 49,
        "sugar_g": 0,
        "category": "bowl",
        "tags": ["salmon", "fish", "bowl", "premium", "bold_flavor"],
    },
    {
        "index": 12,
        "name": "Боул со стейком и острым мёдом",
        "price_rub": 595,
        "calories": 625,
        "protein_g": 33,
        "carbs_g": 48,
        "fat_g": 33,
        "sugar_g": 0,
        "category": "bowl",
        "tags": ["steak", "crunchy", "hot_honey", "premium", "balanced"],
    },
    {
        "index": 13,
        "name": "Салат кейл-цезарь с курицей",
        "price_rub": 490,
        "calories": 490,
        "protein_g": 35,
        "carbs_g": 14,
        "fat_g": 32,
        "sugar_g": 0,
        "category": "salad",
        "tags": ["chicken", "salad", "caesar", "low_carb", "classic"],
    },
    {
        "index": 14,
        "name": "Салат с курицей и гуакамоле",
        "price_rub": 525,
        "calories": 555,
        "protein_g": 23,
        "carbs_g": 35,
        "fat_g": 33,
        "sugar_g": 0,
        "category": "salad",
        "tags": ["chicken", "salad", "avocado", "fresh", "healthy"],
    },
    {
        "index": 15,
        "name": "Зелёный салат «Годдесс»",
        "price_rub": 455,
        "calories": 465,
        "protein_g": 12,
        "carbs_g": 36,
        "fat_g": 31,
        "sugar_g": 8,
        "category": "salad",
        "tags": ["vegetarian", "salad", "greens", "light", "healthy"],
    },
    {
        "index": 16,
        "name": "Салат с курицей и соусом барбекю",
        "price_rub": 490,
        "calories": 545,
        "protein_g": 22,
        "carbs_g": 40,
        "fat_g": 29,
        "sugar_g": 0,
        "category": "salad",
        "tags": ["chicken", "salad", "bbq", "sweet", "casual"],
    },
    {
        "index": 17,
        "name": "Салат с хумусом и хрустящим нутом",
        "price_rub": 455,
        "calories": 390,
        "protein_g": 12,
        "carbs_g": 39,
        "fat_g": 18,
        "sugar_g": 0,
        "category": "salad",
        "tags": ["vegetarian", "salad", "hummus", "light", "mediterranean"],
    },
    {
        "index": 18,
        "name": "Острый салат «Буффало» с курицей",
        "price_rub": 525,
        "calories": 555,
        "protein_g": 31,
        "carbs_g": 32,
        "fat_g": 34,
        "sugar_g": 0,
        "category": "salad",
        "tags": ["chicken", "salad", "spicy", "buffalo", "high_protein"],
    },
    {
        "index": 19,
        "name": "Фокачча с розмарином",
        "price_rub": 140,
        "calories": 230,
        "protein_g": 8,
        "carbs_g": 34,
        "fat_g": 7,
        "sugar_g": 0,
        "category": "side",
        "tags": ["bread", "side", "bakery", "carb"],
    },
    {
        "index": 20,
        "name": "Хумус с фокаччей",
        "price_rub": 210,
        "calories": 290,
        "protein_g": 10,
        "carbs_g": 37,
        "fat_g": 11,
        "sugar_g": 0,
        "category": "side",
        "tags": ["side", "hummus", "bread", "snack"],
    },
    {
        "index": 21,
        "name": "Запечённый батат",
        "price_rub": 175,
        "calories": 340,
        "protein_g": 5,
        "carbs_g": 31,
        "fat_g": 22,
        "sugar_g": 0,
        "category": "side",
        "tags": ["side", "sweet_potato", "warm", "comfort"],
    },
    {
        "index": 22,
        "name": "Десерт из хрустящего риса",
        "price_rub": 140,
        "calories": 190,
        "protein_g": 0,
        "carbs_g": 0,
        "fat_g": 0,
        "sugar_g": 6,
        "category": "dessert",
        "tags": ["dessert", "sweet", "light_snack"],
    },
    {
        "index": 23,
        "name": "Десерт: кешью с ванилью",
        "price_rub": 175,
        "calories": 170,
        "protein_g": 0,
        "carbs_g": 0,
        "fat_g": 0,
        "sugar_g": 4,
        "category": "dessert",
        "tags": ["dessert", "chocolate", "cashew", "snack"],
    },
    {
        "index": 24,
        "name": "Плитка тёмного шоколада с солью",
        "price_rub": 175,
        "calories": 380,
        "protein_g": 0,
        "carbs_g": 0,
        "fat_g": 0,
        "sugar_g": 14,
        "category": "dessert",
        "tags": ["dessert", "chocolate", "sweet"],
    },
    {
        "index": 25,
        "name": "Вода питьевая, негазированная",
        "price_rub": 105,
        "calories": 0,
        "protein_g": 0,
        "carbs_g": 0,
        "fat_g": 0,
        "sugar_g": 0,
        "category": "drink",
        "tags": ["drink", "water", "zero_calorie"],
    },
    {
        "index": 26,
        "name": "Вода минеральная газированная",
        "price_rub": 105,
        "calories": 0,
        "protein_g": 0,
        "carbs_g": 0,
        "fat_g": 0,
        "sugar_g": 0,
        "category": "drink",
        "tags": ["drink", "sparkling", "water", "zero_calorie"],
    },
    {
        "index": 27,
        "name": "Газировка лимон-лайм (мало сахара)",
        "price_rub": 140,
        "calories": 35,
        "protein_g": 0,
        "carbs_g": 16,
        "fat_g": 0,
        "sugar_g": 2,
        "category": "drink",
        "tags": ["drink", "soda", "sweet", "low_calorie"],
    },
    {
        "index": 28,
        "name": "Газировка «кола» (мало сахара)",
        "price_rub": 140,
        "calories": 25,
        "protein_g": 0,
        "carbs_g": 16,
        "fat_g": 0,
        "sugar_g": 4,
        "category": "drink",
        "tags": ["drink", "cola", "sweet", "caffeine"],
    },
    {
        "index": 29,
        "name": "Напиток с малиной и лаймом",
        "price_rub": 140,
        "calories": 5,
        "protein_g": 0,
        "carbs_g": 1,
        "fat_g": 0,
        "sugar_g": 1,
        "category": "drink",
        "tags": ["drink", "sparkling", "berry", "light"],
    },
    {
        "index": 30,
        "name": "Напиток с грейпфрутом",
        "price_rub": 140,
        "calories": 17,
        "protein_g": 0,
        "carbs_g": 4,
        "fat_g": 0,
        "sugar_g": 3,
        "category": "drink",
        "tags": ["drink", "sparkling", "citrus", "light"],
    },
    {
        "index": 31,
        "name": "Зелёный чай с жасмином",
        "price_rub": 140,
        "calories": 0,
        "protein_g": 0,
        "carbs_g": 0,
        "fat_g": 0,
        "sugar_g": 0,
        "category": "drink",
        "tags": ["drink", "tea", "unsweetened", "healthy"],
    },
    {
        "index": 32,
        "name": "Холодный чай: гибискус и ягоды",
        "price_rub": 140,
        "calories": 0,
        "protein_g": 0,
        "carbs_g": 0,
        "fat_g": 0,
        "sugar_g": 0,
        "category": "drink",
        "tags": ["drink", "tea", "berry", "unsweetened"],
    },
    {
        "index": 33,
        "name": "Домашний лимонад",
        "price_rub": 140,
        "calories": 80,
        "protein_g": 0,
        "carbs_g": 20,
        "fat_g": 0,
        "sugar_g": 20,
        "category": "drink",
        "tags": ["drink", "lemonade", "sweet"],
    },
    {
        "index": 34,
        "name": "Комбуча с яблоком",
        "price_rub": 175,
        "calories": 50,
        "protein_g": 0,
        "carbs_g": 12,
        "fat_g": 0,
        "sugar_g": 11,
        "category": "drink",
        "tags": ["drink", "kombucha", "apple", "functional"],
    },
    {
        "index": 35,
        "name": "Комбуча маракуйя и мандарин",
        "price_rub": 175,
        "calories": 50,
        "protein_g": 0,
        "carbs_g": 12,
        "fat_g": 0,
        "sugar_g": 11,
        "category": "drink",
        "tags": ["drink", "kombucha", "fruit", "functional"],
    },
]

_MENU_TASTE_TIME: dict[int, tuple[list[str], list[str]]] = {
    1: (["umami", "sweet"], ["lunch", "dinner"]),
    2: (["umami", "fresh"], ["dinner"]),
    3: (["umami", "sweet"], ["lunch", "dinner"]),
    4: (["sweet", "spicy", "umami"], ["lunch", "dinner"]),
    5: (["umami", "fresh"], ["lunch", "dinner"]),
    6: (["sweet", "fresh"], ["lunch"]),
    7: (["umami", "fresh"], ["lunch", "dinner"]),
    8: (["umami", "fresh"], ["lunch", "dinner"]),
    9: (["fresh", "umami"], ["lunch", "dinner"]),
    10: (["umami", "fresh"], ["lunch", "dinner"]),
    11: (["fresh", "spicy"], ["lunch", "dinner"]),
    12: (["sweet", "umami"], ["dinner"]),
    13: (["fresh", "umami"], ["lunch", "dinner"]),
    14: (["fresh"], ["lunch"]),
    15: (["fresh"], ["lunch"]),
    16: (["sweet", "umami"], ["lunch", "dinner"]),
    17: (["fresh", "umami"], ["lunch", "snack"]),
    18: (["spicy", "fresh"], ["lunch", "dinner"]),
    19: (["fresh"], ["snack", "lunch"]),
    20: (["umami", "fresh"], ["snack", "lunch"]),
    21: (["sweet", "umami"], ["lunch", "dinner", "snack"]),
    22: (["sweet"], ["snack"]),
    23: (["sweet"], ["snack"]),
    24: (["sweet", "umami"], ["snack"]),
    25: (["fresh"], ["lunch", "dinner", "snack"]),
    26: (["fresh"], ["lunch", "dinner", "snack"]),
    27: (["sweet", "fresh"], ["snack", "lunch"]),
    28: (["sweet"], ["snack", "lunch"]),
    29: (["fresh", "sweet"], ["snack", "lunch"]),
    30: (["fresh", "sweet"], ["snack", "lunch"]),
    31: (["fresh"], ["lunch", "snack"]),
    32: (["fresh"], ["lunch", "snack"]),
    33: (["sweet", "fresh"], ["snack", "lunch"]),
    34: (["fresh", "sweet"], ["snack"]),
    35: (["fresh", "sweet"], ["snack"]),
}

for _it in MENU_ITEMS:
    _t, _tf = _MENU_TASTE_TIME[_it["index"]]
    _it["taste"] = list(_t)
    _it["time_fit"] = list(_tf)


def vectorize_menu_item(item: dict) -> list[float]:
    tag_set = set(item["tags"])
    category = item["category"]

    row = [
        float(item.get("price_rub", 0)),
        float(item.get("calories", 0)),
        float(item.get("protein_g", 0)),
        float(item.get("carbs_g", 0)),
        float(item.get("fat_g", 0)),
        float(item.get("sugar_g", 0)),

        1.0 if category == "bowl" else 0.0,
        1.0 if category == "dessert" else 0.0,
        1.0 if category == "drink" else 0.0,
        1.0 if category == "protein_plate" else 0.0,
        1.0 if category == "salad" else 0.0,
        1.0 if category == "side" else 0.0,
    ]

    for tag_feature in TAG_FEATURES:
        tag_name = tag_feature.replace("tag_", "", 1)
        row.append(1.0 if tag_name in tag_set else 0.0)

    return row

MENU_INDEXES = [item["index"] for item in MENU_ITEMS]
MENU_NAMES = [item["name"] for item in MENU_ITEMS]

X_MENU = np.array([vectorize_menu_item(item) for item in MENU_ITEMS], dtype=np.float32)

food_payload = {
    "feature_names": FEATURE_NAMES,
    "menu_indexes": MENU_INDEXES,
    "menu_names": MENU_NAMES,
    "menu_items": MENU_ITEMS,
    "x_menu": X_MENU.tolist(),
}

with Path("food.json").open("w", encoding="utf-8") as f:
    json.dump(food_payload, f, ensure_ascii=False, indent=2)

print("X_MENU shape:", X_MENU.shape)
print("features:", len(FEATURE_NAMES))
print("first item:", MENU_NAMES[0])
print("first vector:", X_MENU[0])